I don't know how I expected this to work without defining the variable. Also switch to RuntimeError so things like this don't show up as a problem here:
  NoMethodError: undefined method `keep_if' for nil:NilClass
    /home/okeeblow/Works/DistorteD/DistorteD-Jekyll/lib/distorted-jekyll/molecule/abstract.rb:120:in `attrs'